---
title: 'Cover Letter : 2023년 상반기'
author: "sung won kang"
date: '2023-05-25'
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
  word_document: default
mainfont: NanumGothic
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2023년 상반기 환경 데이터 뉴스레터의 주요 내용은 다음과 같다.

#### 1.텍스트 분석

> 2023년 1월 -6월에 게시된 네이버 환경뉴스를 분석한 결과 당시 국민들은 한파(1월), 미세먼지(3월), 황사(3월), 산불(3,4월),지진(5월) 등 극단적 기후현성 및 자연재해, 설악산 오색삭도(2월), 후쿠시마 원전 오염수 방류(2월,4월,5월,6월)에 대한 관심이 많았음을 유추할 수 있었다. 반면, 이 시기 환경부 문헌의 키워드에는 미세먼지 정책의 성과(5월)에 관련된 키워드를 제외하고는 이상 네이버 환경뉴스에서 빈번하게 파악되었던 키워드들이  파악되지 않았다. 

> 그리고 환경부 문헌의 키워드로 부터 당시 환경부는 유해화학물질 배출시설 현황파악 및 관리(1월), 녹색경제 활성화(2월,4월,5월,6월), 환경규제 개선(2월,6월), 멸종위기종 보호(3월,5월), 국립공원 활용 증진(3월,5월,6월), 환경안전 강화(4월), 가뭄 대비 용수 공급(3월,4월,5월) 정책을 주로 수행하고 있었음을 파악할 수 있었다. 이들 정책 중 녹색경제 활성화 정책은 NAVER 키워드에서 비중이 높았던 '기후' 와 관련된 국민들의 관심에 조응하는 정책이라고 할 수 있다. 반면 여타 관련된 키워드는 네이버 뉴스 키워드에서는 찾기 어려웠다. 

>특히 후쿠시마 원전 오염수 방류 관련 네이버 환경뉴스는 2월, 4월, 5월,6월 4개월에 걸쳐서 관련 키워드의 출현 빈도가 높은 이슈였지만, 환경부 문헌에는 이 이슈 관련 키워드를 포함하는 문헌이 드물었다.  



자세한 텍스트 분석 결과는 아래에 링크된 월별 텍스트 분석 결과에서 찾아볼 수 있다.

* [**텍스트 분석 뉴스 레터: 2023년 1월**](./Textanal/textanalysis_230516_2023JAN.html)

* [**텍스트 분석 뉴스 레터: 2023년 2월**](./Textanal/textanalysis_230516_2023FEB.html)

* [**텍스트 분석 뉴스 레터: 2023년 3월**](./Textanal/textanalysis_230516_2023March.html)

* [**텍스트 분석 뉴스 레터: 2023년 4월**](./Textanal/textanalysis_230516APR.html)

* [**텍스트 분석 뉴스 레터: 2023년 5월**](./Textanal/textanalysis_230516_2023MAY.html)

* [**텍스트 분석 뉴스 레터: 2023년 6월**](./Textanal/textanalysis_230703JUNE.html)